### ISSUE TITLE
Filtering argument issues in search method

### ISSUE THREAD

**Issue by sky-2002** [NeumTry/NeumAI#50]
@ddematheu 
1. Currently, the `filter` argument in `SinkConnector.search` method expects the following - 
`filters:List[FilterCondition]={}`, it should rather be `filters:List[dict]={}` and then we need to convert the `dict` to a `FilterCondition` using `dict_to_filter_condition`. Because user would provide a dictionary not a `FilterCondition` object. 
2. Also, there needs to be consistency in naming the filtering argument because at some places it is `filter` and some other places it is `filters`. 
Let me know your opinion on this, and I will open a PR.

**Comment by ddematheu** [comment]
On #1, not sure if I agree. I think that expecting the actual object makes the interface more robust. But open to feedback. btw since the FilterCondition is a pydantic basemodel you no longer need the dict to filter condition method, instead can do FilterCondition(**dict)

On #2 thanks for pointing this out. Will generate a fix for this.

**Comment by ddematheu** [comment]
Just opened PR with fix for #2.

**Comment by sky-2002** [comment]
@ddematheu Great, I think that solves this issue.
